---
# handlers file for ansible_role_web

- name: Control web server
  ansible.builtin.systemd:
    name: "{{ webserver }}"
    state: "{{ web_systemd_state }}"
    enabled: "{{ web_enabled_state }}"
    daemon_reload: true
