# This is an example playbook to execute Ansible tests.
---
- name: Cleanup
  hosts: all
  gather_facts: false
  vars:
    desired_state: "absent"
  tasks:
    - name: "Include ansible_role_web"
      ansible.builtin.include_role:
        name: "ansible_role_web"
