# This is an example playbook to prepare Ansible tests.
---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include ansible_role_web"
      ansible.builtin.include_role:
        name: "ansible_role_web"
        tasks_from: prepare
